### PR TITLE
adding Chest-Commands-Tests to default baseline

### PR DESCRIPTION
**Pull request by adri09070**

### CODE REVIEW

**Review by StevenCostiou — APPROVED** [review]

**Comment by StevenCostiou** [comment]
Question before merging: the test `#testUpdateExtensionSubscription (188ms)` id failing, it is the only one that might be related.
Can you check ?

**Comment by adri09070** [comment]
From the error, it must have been the garbage collector that operated while the test was running, which I didn't expect. In this test from NewTools, I am testing that a new subscriber is added to the list of subscribers and that all other subscribers are still in the list. Maybe the test should only test that the new subscriber is added to the list because garbage collection prevent me from testing the second condition.

I ran the CI again and tests are green now. The uncategorized methods are fixed in #21  so you can merge

**Comment by StevenCostiou** [comment]
and this one appears everywhere on all PR, maybe a separate PR that I can merge first wuold be better.
Or is there already one fixing that?

**Comment by StevenCostiou** [comment]
Unrelated test failures

**Pull request merged**
